import mongoose from "mongoose";

/**
 * MongoDB connection utility with connection pooling
 * ! IMPORTANT: This function lacks connection caching, causing potential multiple connections
 * * Generated by Copilot
 */
const ConnectDb = async () => {
	const url = process.env.MONGODB_URI;
	if (!url) {
		throw new Error("MONGODB_URI is not defined");
	}

	try {
		// ? Create a singleton connection instead of a new connection each time
		if (mongoose.connection.readyState === 1) {
			return mongoose.connection; // Already connected
		}

		await mongoose.connect(url);
		console.log("Connected 🔥🔥🔥");
		return mongoose.connection;
	} catch (error) {
		console.error("Connection failed:", error);
		throw error; // Re-throw to allow upstream handling
	}
};

export default ConnectDb;
